juttle/juttle-influx-adapter

README.md

Basic authentication can be performed via the URL key in the config file. Document this possibility.

Document basic auth via client

---

lib/ast/lint.js
test/ast/lint.spec.js

The MomentContstant and DurationConstant were renamed to MomentLiteral
and DurationLiteral, respectively. Update the checks prohibiting
filtering on time and the tests to reflect that.
Also remove names of AST nodes which would not occur in a 'real' world
scenarios - they're converted by a semantic pass.

Fix filter AST lint dealing with time

---

index.js

As read now inherits from Juttle source proc and program checks for
that, the sourceType property is not needed.
refs: https://github.com/juttle/juttle/pull/110

Drop sourceType property from read

---

index.js
test/influx-live.spec.js

JuttleMoment.compare now accepts only two operands (values to compare)
and returns -1, 0, 1 for lt/eq/gt values. Adapt the code for that.

Update to reflect JuttleMoment compare API change

---

lib/serializer.js
test/influx-live.spec.js
test/serializer.spec.js

As core Juttle now handles fields whose values are arrays or objects,
add support for serializing those points into JSON.

Add support for serializing objects/arrays

---

.travis.yml

Fix a simple typo in which the node_js section was duplicated.
@bkutil

travis: remove duplicate node_js section

---

lib/read.js

The URL option is global and constant, so it does not make sense to
validate it during every call to fetch. Instead validate it once, during
adapter read construction.

read.js - move URL validation to constructor

---

lib/query/select.js
lib/read.js
test/influx-live.spec.js

Instead of handling 'raw' option (containing a query string) in read,
pass that option along to query builder and let it decide what to do -
in this case, just return the query string back.

read.js - handle 'raw' option in querybuilder

---

lib/read.js
test/influx-live.spec.js

Implement validation of time options according to the spec for big-data
adapters published here:
https://github.com/juttle/juttle/wiki/Time-Range-Semantics
For now, do not handle -last option and use native JS errors until
we decide on how to handle errors in adapters.

Time range semantics

---

lib/query/select.js
lib/query/time-filter.js
lib/query/where.js
test/query/query.spec.js

Fix edge case triggered when 'nameField' gets filtered out from the
filter AST, where clause is thus equal to undefined and from / to is
specified.
Time-filter was not be able to cope with undefineds - it stringified it,
instead of starting with an empty string.

time-filter.js - fix time handling w/o where

---

.eslintrc
lib/ast/lint.js
lib/ast/rewrite.js
lib/ast/rewrite/in.js
lib/ast/rewrite/not.js
lib/query/from.js
lib/query/select.js
lib/query/time-filter.js
lib/query/where.js
lib/read.js
lib/serializer.js
lib/write.js
test/influx-live.spec.js

This builds on the core of #42.
As changing the API requires switching to ES6 classes (there is no equivalent ES5 way how to inherit from Adapter Read/Write on an ES6 runtime), first switch the whole project to start using them consistently across the board, then implement changes required to move to the new API in read/write and finally rename read/write classes to be consistent with other adapters.

Adapter api

---

index.js
lib/query/optimize.js
lib/query/select.js
lib/read.js
test/influx-live.spec.js
test/query/query.spec.js

Add support for head and tail optimisations and tests. `tail by` and `head by` are not supported.
refs: #39

Optimize head and tail

---

lib/read.js
lib/write.js
test/influx-live.spec.js

Instead of throwing native JS errors, ensure we use Juttle error classes
consistently in public facing APIs.

Switch to Juttle errors in public APIs

---

.travis.yml

To avoid tests breaking due to an upstream change in the middle of
release cycle, test against stable version of juttle core.
During a new release, the version in .travis.yml will be updated to
the new upstream version, and breaking changes adressed in one go.

Travis - test against stable version of juttle

---

lib/read.js

Influx always returns time, even for selects that explicitly don't list
that field. So it is safe to use native Juttle sort.

read.js - points always contain time

---

lib/serializer.js
test/serializer.spec.js

Influx doesn't support writing nulls and regexp data types.

Disallow writes of null and regexp values

---

lib/ast/lint.js
test/ast/lint.spec.js
test/query/query.spec.js

It is not consistently supported by influx DB
Fixes: #73

Disallow filtering on null

---

lib/ast/rewrite/in.js
test/influx-integration.spec.js

Certain issues are not in the adapter, but are caused by an underlying bug
in influx. Add links to the upstream bugs on github.

Annotate code with references to upstream bugs

---

.travis.yml

Enable travis builds for juttle master, but allow them to fail. This should serve as an early warning against breaking changes in core.

Travis build matrix

---

lib/read.js
test/influx-integration.spec.js

Remove redundant if. Checking once for the same thing should be enough for everybody. Also add test for time range options.

Remove redundant condition

---

lib/read.js
lib/write.js

AdapterRead and AdapterWrite expose error helpers in the base classes.
Use them instead of importing error related functions from the Adapter
API.

Use error helpers instead of calling error.X methods

---

lib/write.js

Influx times out on writing ~200k points during a single request.
Split the body into chunks of 10k points and send the requests
separately.
What we lose by this is that if single request fails, the previous
writes are not rolled back.

write.js: split data into chunks on write

---

README.md
lib/read.js
test/influx-integration.spec.js

There was a bug in read that caused only 1k of points to be fetched by
default.
Update the limit-handling code so that:
1. User choices override optimization settings
2. When base class calls `read()` to fetch more points, we keep track
of points fetched, and compute the limit as a minimum from the
`batchSize` parameter passed to us and the remaining points to be
read in total.

read.js - fix handling of query limits

---

lib/ast/lint.js
test/ast/lint.spec.js

There was a stray require() which wasn't properly converted to the
new Adapter API so it failed when juttle wasn't resolvable in the
require path.

lint: use global JuttleAdapterAPI

---

test/influx-integration.spec.js

The `deactivateAfter` was changed from a parameter to an option.
Update live tests to reflect that.

influx-integration.spec.js - fix delayed deactivation of tests

---

lib/serializer.js
lib/write.js
package.json
test/influx-integration.spec.js
test/performance/index.js
test/performance/serializer/influx.js
test/performance/serializer/juttle.js
test/performance/write/live.js
test/performance/write/serialize.js
test/performance/write/stubbed.js
test/test_utils.js
test/test_utils/db.js
test/test_utils/index.js
test/test_utils/parse_filter.js

The benchmarks can be run using `npm run-script -s perf`.

Add performance tests for influx serialization
